# Generated by Django 4.2.21 on 2026-04-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Blue Solutions', help_text='Your business name — shows in browser tab and footer.', max_length=100)),
                ('tagline', models.CharField(default='Architecture & Interior Design', help_text='Short description under your logo.', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Logo for dark backgrounds (white/light version). PNG with transparency works best.', null=True, upload_to='site/')),
                ('logo_light', models.ImageField(blank=True, help_text='Logo for light/white backgrounds (dark version).', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Tiny icon shown in browser tabs. Should be square, at least 32×32px.', null=True, upload_to='site/')),
                ('hero_label', models.CharField(default='OUR WORKS', help_text='Small label above the main headline on the homepage.', max_length=100)),
                ('hero_heading', models.CharField(default='AWESOME DESIGNS', help_text='Big headline on the homepage hero.', max_length=200)),
                ('hero_video_url', models.URLField(blank=True, default='https://vimeo.com/175353205', help_text='Vimeo or YouTube link for the homepage background video.')),
                ('years_experience', models.PositiveSmallIntegerField(default=25, help_text='Number shown in the "Years of Experience" counter.')),
                ('projects_count', models.PositiveSmallIntegerField(default=50, help_text='Number shown in the "Projects Completed" counter.')),
                ('about_label', models.CharField(default='About Studio', help_text='Small label above the about heading.', max_length=100)),
                ('about_heading', models.CharField(default='Welcome! We are an architecture studio', help_text='Main heading in the About section.', max_length=200)),
                ('about_text', models.TextField(blank=True, help_text='Paragraph describing your studio. Shown on homepage and About page.')),
                ('about_image', models.ImageField(blank=True, help_text='Primary about/studio photo.', null=True, upload_to='site/')),
                ('about_image2', models.ImageField(blank=True, help_text='Secondary about/studio photo (shown alongside the first).', null=True, upload_to='site/')),
                ('founded_year', models.PositiveSmallIntegerField(default=2000, help_text='Year your studio was founded.')),
                ('process_1_title', models.CharField(default='Idea & Start', max_length=100)),
                ('process_1_desc', models.TextField(blank=True, default='We listen to your vision and define the project goals.')),
                ('process_2_title', models.CharField(default='Design & Create', max_length=100)),
                ('process_2_desc', models.TextField(blank=True, default='Our team drafts concepts and refines them with your feedback.')),
                ('process_3_title', models.CharField(default='Build & Finish', max_length=100)),
                ('process_3_desc', models.TextField(blank=True, default='We bring the design to life with precision and care.')),
                ('contact_phone', models.CharField(blank=True, help_text='Phone number shown on contact page and footer.', max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Email address for the contact form destination and display.', max_length=254)),
                ('contact_address', models.CharField(blank=True, help_text='Street address.', max_length=200)),
                ('contact_city', models.CharField(blank=True, help_text='City, State ZIP — shown below address.', max_length=100)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL. Go to maps.google.com → find your location → Share → Embed a map → copy the src="..." URL.')),
                ('social_instagram', models.URLField(blank=True, help_text='Full URL e.g. https://instagram.com/yourstudio')),
                ('social_facebook', models.URLField(blank=True, help_text='Full URL e.g. https://facebook.com/yourstudio')),
                ('social_twitter', models.URLField(blank=True, help_text='Full URL e.g. https://twitter.com/yourstudio')),
                ('social_linkedin', models.URLField(blank=True, help_text='Full URL e.g. https://linkedin.com/company/yourstudio')),
                ('social_behance', models.URLField(blank=True, help_text='Full URL e.g. https://behance.net/yourstudio')),
                ('social_dribbble', models.URLField(blank=True, help_text='Full URL e.g. https://dribbble.com/yourstudio')),
                ('footer_tagline', models.CharField(blank=True, help_text='Short line shown in the footer under your logo.', max_length=200)),
                ('copyright_name', models.CharField(default='Blue Solutions', help_text='Name used in the footer copyright line.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
