# Generated by Django 4.2.21 on 2026-04-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='page_about',
            field=models.BooleanField(default=True, help_text='Show the About page (/about/).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='page_contact',
            field=models.BooleanField(default=True, help_text='Show the Contact page (/contact/).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='page_home',
            field=models.BooleanField(default=True, help_text='Show the homepage (/) with hero slider and featured projects.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='page_portfolio',
            field=models.BooleanField(default=True, help_text='Show the Portfolio page (/portfolio/).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_about',
            field=models.BooleanField(default=True, help_text='Show the About Studio section on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_blog',
            field=models.BooleanField(default=False, help_text='Show the Latest News/Blog section on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_contact_cta',
            field=models.BooleanField(default=True, help_text='Show the "Let\'s Talk" contact call-to-action at the bottom of the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_services',
            field=models.BooleanField(default=True, help_text='Show the Services/Features strip on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_testimonials',
            field=models.BooleanField(default=True, help_text='Show the client testimonials carousel on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_video',
            field=models.BooleanField(default=True, help_text='Show the video/awards block on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_works',
            field=models.BooleanField(default=True, help_text='Show the Our Works project slider on the homepage.'),
        ),
    ]
